/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AssocitationFieldItem;
import io.swagger.client.model.DependencyFieldItem;
import io.swagger.client.model.FieldBaseDTO;
import java.io.IOException;
import java.util.List;

/**
 * Class of additional field for Decimal type
 */
@ApiModel(description = "Class of additional field for Decimal type")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AdditionalFieldDoubleDTO extends FieldBaseDTO {
  @SerializedName("value")
  private Double value = null;

  @SerializedName("decimals")
  private Integer decimals = null;

  @SerializedName("additionalFieldType")
  private Integer additionalFieldType = null;

  @SerializedName("groupId")
  private Integer groupId = null;

  @SerializedName("binderFieldId")
  private Integer binderFieldId = null;

  @SerializedName("taskWorkVariableId")
  private Integer taskWorkVariableId = null;

  public AdditionalFieldDoubleDTO value(Double value) {
    this.value = value;
    return this;
  }

   /**
   * Value
   * @return value
  **/
  @ApiModelProperty(value = "Value")
  public Double getValue() {
    return value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

  public AdditionalFieldDoubleDTO decimals(Integer decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * Decimals number
   * @return decimals
  **/
  @ApiModelProperty(value = "Decimals number")
  public Integer getDecimals() {
    return decimals;
  }

  public void setDecimals(Integer decimals) {
    this.decimals = decimals;
  }

  public AdditionalFieldDoubleDTO additionalFieldType(Integer additionalFieldType) {
    this.additionalFieldType = additionalFieldType;
    return this;
  }

   /**
   * Possible values:  0: Textbox  1: Databox  2: Numeric  3: Combobox  4: TableBox  5: Checkbox  6: MultiValue  7: ClasseBox  8: Group  9: RubricaBox  10: TextArea 
   * @return additionalFieldType
  **/
  @ApiModelProperty(value = "Possible values:  0: Textbox  1: Databox  2: Numeric  3: Combobox  4: TableBox  5: Checkbox  6: MultiValue  7: ClasseBox  8: Group  9: RubricaBox  10: TextArea ")
  public Integer getAdditionalFieldType() {
    return additionalFieldType;
  }

  public void setAdditionalFieldType(Integer additionalFieldType) {
    this.additionalFieldType = additionalFieldType;
  }

  public AdditionalFieldDoubleDTO groupId(Integer groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Group Identifier
   * @return groupId
  **/
  @ApiModelProperty(value = "Group Identifier")
  public Integer getGroupId() {
    return groupId;
  }

  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  public AdditionalFieldDoubleDTO binderFieldId(Integer binderFieldId) {
    this.binderFieldId = binderFieldId;
    return this;
  }

   /**
   * Binder Field Identifier
   * @return binderFieldId
  **/
  @ApiModelProperty(value = "Binder Field Identifier")
  public Integer getBinderFieldId() {
    return binderFieldId;
  }

  public void setBinderFieldId(Integer binderFieldId) {
    this.binderFieldId = binderFieldId;
  }

  public AdditionalFieldDoubleDTO taskWorkVariableId(Integer taskWorkVariableId) {
    this.taskWorkVariableId = taskWorkVariableId;
    return this;
  }

   /**
   * Variable Identifier in taskword context
   * @return taskWorkVariableId
  **/
  @ApiModelProperty(value = "Variable Identifier in taskword context")
  public Integer getTaskWorkVariableId() {
    return taskWorkVariableId;
  }

  public void setTaskWorkVariableId(Integer taskWorkVariableId) {
    this.taskWorkVariableId = taskWorkVariableId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalFieldDoubleDTO additionalFieldDoubleDTO = (AdditionalFieldDoubleDTO) o;
    return Objects.equals(this.value, additionalFieldDoubleDTO.value) &&
        Objects.equals(this.decimals, additionalFieldDoubleDTO.decimals) &&
        Objects.equals(this.additionalFieldType, additionalFieldDoubleDTO.additionalFieldType) &&
        Objects.equals(this.groupId, additionalFieldDoubleDTO.groupId) &&
        Objects.equals(this.binderFieldId, additionalFieldDoubleDTO.binderFieldId) &&
        Objects.equals(this.taskWorkVariableId, additionalFieldDoubleDTO.taskWorkVariableId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, decimals, additionalFieldType, groupId, binderFieldId, taskWorkVariableId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalFieldDoubleDTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    additionalFieldType: ").append(toIndentedString(additionalFieldType)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    binderFieldId: ").append(toIndentedString(binderFieldId)).append("\n");
    sb.append("    taskWorkVariableId: ").append(toIndentedString(taskWorkVariableId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

