/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * This is the DTO for a AddreBook note item
 */
@ApiModel(description = "This is the DTO for a AddreBook note item")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AddressBookNoteDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("addressBookId")
  private Integer addressBookId = null;

  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("authorCompleteName")
  private String authorCompleteName = null;

  @SerializedName("author")
  private Integer author = null;

  @SerializedName("note")
  private String note = null;

  public AddressBookNoteDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the note
   * @return id
  **/
  @ApiModelProperty(value = "Id of the note")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AddressBookNoteDTO addressBookId(Integer addressBookId) {
    this.addressBookId = addressBookId;
    return this;
  }

   /**
   * System id of the addressbook item
   * @return addressBookId
  **/
  @ApiModelProperty(value = "System id of the addressbook item")
  public Integer getAddressBookId() {
    return addressBookId;
  }

  public void setAddressBookId(Integer addressBookId) {
    this.addressBookId = addressBookId;
  }

  public AddressBookNoteDTO date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Creation date of the note
   * @return date
  **/
  @ApiModelProperty(value = "Creation date of the note")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public AddressBookNoteDTO authorCompleteName(String authorCompleteName) {
    this.authorCompleteName = authorCompleteName;
    return this;
  }

   /**
   * Author Complete name
   * @return authorCompleteName
  **/
  @ApiModelProperty(value = "Author Complete name")
  public String getAuthorCompleteName() {
    return authorCompleteName;
  }

  public void setAuthorCompleteName(String authorCompleteName) {
    this.authorCompleteName = authorCompleteName;
  }

  public AddressBookNoteDTO author(Integer author) {
    this.author = author;
    return this;
  }

   /**
   * Author of the note
   * @return author
  **/
  @ApiModelProperty(value = "Author of the note")
  public Integer getAuthor() {
    return author;
  }

  public void setAuthor(Integer author) {
    this.author = author;
  }

  public AddressBookNoteDTO note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Text of the note
   * @return note
  **/
  @ApiModelProperty(value = "Text of the note")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressBookNoteDTO addressBookNoteDTO = (AddressBookNoteDTO) o;
    return Objects.equals(this.id, addressBookNoteDTO.id) &&
        Objects.equals(this.addressBookId, addressBookNoteDTO.addressBookId) &&
        Objects.equals(this.date, addressBookNoteDTO.date) &&
        Objects.equals(this.authorCompleteName, addressBookNoteDTO.authorCompleteName) &&
        Objects.equals(this.author, addressBookNoteDTO.author) &&
        Objects.equals(this.note, addressBookNoteDTO.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, addressBookId, date, authorCompleteName, author, note);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressBookNoteDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    addressBookId: ").append(toIndentedString(addressBookId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    authorCompleteName: ").append(toIndentedString(authorCompleteName)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

