/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RubricaFieldDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AddressBookSearchCriteriaDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AddressBookSearchCriteriaDTO {
  @SerializedName("addressBookCategoryId")
  private Integer addressBookCategoryId = null;

  @SerializedName("filterFields")
  private List<RubricaFieldDTO> filterFields = null;

  @SerializedName("selectFields")
  private List<RubricaFieldDTO> selectFields = null;

  @SerializedName("filter")
  private String filter = null;

  public AddressBookSearchCriteriaDTO addressBookCategoryId(Integer addressBookCategoryId) {
    this.addressBookCategoryId = addressBookCategoryId;
    return this;
  }

   /**
   * Get addressBookCategoryId
   * @return addressBookCategoryId
  **/
  @ApiModelProperty(value = "")
  public Integer getAddressBookCategoryId() {
    return addressBookCategoryId;
  }

  public void setAddressBookCategoryId(Integer addressBookCategoryId) {
    this.addressBookCategoryId = addressBookCategoryId;
  }

  public AddressBookSearchCriteriaDTO filterFields(List<RubricaFieldDTO> filterFields) {
    this.filterFields = filterFields;
    return this;
  }

  public AddressBookSearchCriteriaDTO addFilterFieldsItem(RubricaFieldDTO filterFieldsItem) {
    if (this.filterFields == null) {
      this.filterFields = new ArrayList<RubricaFieldDTO>();
    }
    this.filterFields.add(filterFieldsItem);
    return this;
  }

   /**
   * Get filterFields
   * @return filterFields
  **/
  @ApiModelProperty(value = "")
  public List<RubricaFieldDTO> getFilterFields() {
    return filterFields;
  }

  public void setFilterFields(List<RubricaFieldDTO> filterFields) {
    this.filterFields = filterFields;
  }

  public AddressBookSearchCriteriaDTO selectFields(List<RubricaFieldDTO> selectFields) {
    this.selectFields = selectFields;
    return this;
  }

  public AddressBookSearchCriteriaDTO addSelectFieldsItem(RubricaFieldDTO selectFieldsItem) {
    if (this.selectFields == null) {
      this.selectFields = new ArrayList<RubricaFieldDTO>();
    }
    this.selectFields.add(selectFieldsItem);
    return this;
  }

   /**
   * Get selectFields
   * @return selectFields
  **/
  @ApiModelProperty(value = "")
  public List<RubricaFieldDTO> getSelectFields() {
    return selectFields;
  }

  public void setSelectFields(List<RubricaFieldDTO> selectFields) {
    this.selectFields = selectFields;
  }

  public AddressBookSearchCriteriaDTO filter(String filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @ApiModelProperty(value = "")
  public String getFilter() {
    return filter;
  }

  public void setFilter(String filter) {
    this.filter = filter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressBookSearchCriteriaDTO addressBookSearchCriteriaDTO = (AddressBookSearchCriteriaDTO) o;
    return Objects.equals(this.addressBookCategoryId, addressBookSearchCriteriaDTO.addressBookCategoryId) &&
        Objects.equals(this.filterFields, addressBookSearchCriteriaDTO.filterFields) &&
        Objects.equals(this.selectFields, addressBookSearchCriteriaDTO.selectFields) &&
        Objects.equals(this.filter, addressBookSearchCriteriaDTO.filter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressBookCategoryId, filterFields, selectFields, filter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressBookSearchCriteriaDTO {\n");
    
    sb.append("    addressBookCategoryId: ").append(toIndentedString(addressBookCategoryId)).append("\n");
    sb.append("    filterFields: ").append(toIndentedString(filterFields)).append("\n");
    sb.append("    selectFields: ").append(toIndentedString(selectFields)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

