/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of the adress book item category
 */
@ApiModel(description = "Class of the adress book item category")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AddressBookCategoryDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("addressBook")
  private String addressBook = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("default")
  private Boolean _default = null;

  public AddressBookCategoryDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier
   * @return id
  **/
  @ApiModelProperty(value = "Identifier")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AddressBookCategoryDTO addressBook(String addressBook) {
    this.addressBook = addressBook;
    return this;
  }

   /**
   * Name
   * @return addressBook
  **/
  @ApiModelProperty(value = "Name")
  public String getAddressBook() {
    return addressBook;
  }

  public void setAddressBook(String addressBook) {
    this.addressBook = addressBook;
  }

  public AddressBookCategoryDTO type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Possible values:  0: Public  1: Private 
   * @return type
  **/
  @ApiModelProperty(value = "Possible values:  0: Public  1: Private ")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public AddressBookCategoryDTO _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * Set as default category
   * @return _default
  **/
  @ApiModelProperty(value = "Set as default category")
  public Boolean isDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressBookCategoryDTO addressBookCategoryDTO = (AddressBookCategoryDTO) o;
    return Objects.equals(this.id, addressBookCategoryDTO.id) &&
        Objects.equals(this.addressBook, addressBookCategoryDTO.addressBook) &&
        Objects.equals(this.type, addressBookCategoryDTO.type) &&
        Objects.equals(this._default, addressBookCategoryDTO._default);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, addressBook, type, _default);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressBookCategoryDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    addressBook: ").append(toIndentedString(addressBook)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

