/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * Class of Attachment
 */
@ApiModel(description = "Class of Attachment")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AttachmentDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("docnumber")
  private Integer docnumber = null;

  @SerializedName("revision")
  private Integer revision = null;

  @SerializedName("filename")
  private String filename = null;

  @SerializedName("filepath")
  private String filepath = null;

  @SerializedName("originalname")
  private String originalname = null;

  @SerializedName("device")
  private Integer device = null;

  @SerializedName("cdlabel")
  private String cdlabel = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("importdate")
  private DateTime importdate = null;

  @SerializedName("user")
  private Integer user = null;

  @SerializedName("userCompleteName")
  private String userCompleteName = null;

  @SerializedName("block")
  private Integer block = null;

  @SerializedName("compliantcopy")
  private Boolean compliantcopy = null;

  @SerializedName("footprint")
  private String footprint = null;

  @SerializedName("checksend")
  private Boolean checksend = null;

  @SerializedName("aosflag")
  private Boolean aosflag = null;

  @SerializedName("access")
  private Integer access = null;

  @SerializedName("saveType")
  private Integer saveType = null;

  @SerializedName("filesize")
  private Long filesize = null;

  @SerializedName("kind")
  private Integer kind = null;

  @SerializedName("attachedDocnumber")
  private Integer attachedDocnumber = null;

  @SerializedName("ixCheck")
  private Boolean ixCheck = null;

  @SerializedName("attachmentRevision")
  private Integer attachmentRevision = null;

  @SerializedName("compressionMode")
  private Integer compressionMode = null;

  public AttachmentDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AttachmentDTO docnumber(Integer docnumber) {
    this.docnumber = docnumber;
    return this;
  }

   /**
   * Document Identifier
   * @return docnumber
  **/
  @ApiModelProperty(value = "Document Identifier")
  public Integer getDocnumber() {
    return docnumber;
  }

  public void setDocnumber(Integer docnumber) {
    this.docnumber = docnumber;
  }

  public AttachmentDTO revision(Integer revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Revision number
   * @return revision
  **/
  @ApiModelProperty(value = "Revision number")
  public Integer getRevision() {
    return revision;
  }

  public void setRevision(Integer revision) {
    this.revision = revision;
  }

  public AttachmentDTO filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Name for the zip file.
   * @return filename
  **/
  @ApiModelProperty(value = "Name for the zip file.")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public AttachmentDTO filepath(String filepath) {
    this.filepath = filepath;
    return this;
  }

   /**
   * Path of compressed file.
   * @return filepath
  **/
  @ApiModelProperty(value = "Path of compressed file.")
  public String getFilepath() {
    return filepath;
  }

  public void setFilepath(String filepath) {
    this.filepath = filepath;
  }

  public AttachmentDTO originalname(String originalname) {
    this.originalname = originalname;
    return this;
  }

   /**
   * Name of the file.
   * @return originalname
  **/
  @ApiModelProperty(value = "Name of the file.")
  public String getOriginalname() {
    return originalname;
  }

  public void setOriginalname(String originalname) {
    this.originalname = originalname;
  }

  public AttachmentDTO device(Integer device) {
    this.device = device;
    return this;
  }

   /**
   * Possible values:  0: Hd  1: Cd 
   * @return device
  **/
  @ApiModelProperty(value = "Possible values:  0: Hd  1: Cd ")
  public Integer getDevice() {
    return device;
  }

  public void setDevice(Integer device) {
    this.device = device;
  }

  public AttachmentDTO cdlabel(String cdlabel) {
    this.cdlabel = cdlabel;
    return this;
  }

   /**
   * CD Label
   * @return cdlabel
  **/
  @ApiModelProperty(value = "CD Label")
  public String getCdlabel() {
    return cdlabel;
  }

  public void setCdlabel(String cdlabel) {
    this.cdlabel = cdlabel;
  }

  public AttachmentDTO comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Description
   * @return comment
  **/
  @ApiModelProperty(value = "Description")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AttachmentDTO importdate(DateTime importdate) {
    this.importdate = importdate;
    return this;
  }

   /**
   * Creation Date
   * @return importdate
  **/
  @ApiModelProperty(value = "Creation Date")
  public DateTime getImportdate() {
    return importdate;
  }

  public void setImportdate(DateTime importdate) {
    this.importdate = importdate;
  }

  public AttachmentDTO user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * Identifier of the author
   * @return user
  **/
  @ApiModelProperty(value = "Identifier of the author")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public AttachmentDTO userCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
    return this;
  }

   /**
   * Full name of the author
   * @return userCompleteName
  **/
  @ApiModelProperty(value = "Full name of the author")
  public String getUserCompleteName() {
    return userCompleteName;
  }

  public void setUserCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
  }

  public AttachmentDTO block(Integer block) {
    this.block = block;
    return this;
  }

   /**
   * Possible values:  0: None  1: Active  2: Marked 
   * @return block
  **/
  @ApiModelProperty(value = "Possible values:  0: None  1: Active  2: Marked ")
  public Integer getBlock() {
    return block;
  }

  public void setBlock(Integer block) {
    this.block = block;
  }

  public AttachmentDTO compliantcopy(Boolean compliantcopy) {
    this.compliantcopy = compliantcopy;
    return this;
  }

   /**
   * Replace with the profile data for web visualization
   * @return compliantcopy
  **/
  @ApiModelProperty(value = "Replace with the profile data for web visualization")
  public Boolean isCompliantcopy() {
    return compliantcopy;
  }

  public void setCompliantcopy(Boolean compliantcopy) {
    this.compliantcopy = compliantcopy;
  }

  public AttachmentDTO footprint(String footprint) {
    this.footprint = footprint;
    return this;
  }

   /**
   * Hash of the file
   * @return footprint
  **/
  @ApiModelProperty(value = "Hash of the file")
  public String getFootprint() {
    return footprint;
  }

  public void setFootprint(String footprint) {
    this.footprint = footprint;
  }

  public AttachmentDTO checksend(Boolean checksend) {
    this.checksend = checksend;
    return this;
  }

   /**
   * Send the file in the case of email shipment
   * @return checksend
  **/
  @ApiModelProperty(value = "Send the file in the case of email shipment")
  public Boolean isChecksend() {
    return checksend;
  }

  public void setChecksend(Boolean checksend) {
    this.checksend = checksend;
  }

  public AttachmentDTO aosflag(Boolean aosflag) {
    this.aosflag = aosflag;
    return this;
  }

   /**
   * Kept in the replacement mode with the document profile
   * @return aosflag
  **/
  @ApiModelProperty(value = "Kept in the replacement mode with the document profile")
  public Boolean isAosflag() {
    return aosflag;
  }

  public void setAosflag(Boolean aosflag) {
    this.aosflag = aosflag;
  }

  public AttachmentDTO access(Integer access) {
    this.access = access;
    return this;
  }

   /**
   * Possible values:  0: Access_Denied  1: Read_Only  2: Edit  4: Full_Trust  -1: None 
   * @return access
  **/
  @ApiModelProperty(value = "Possible values:  0: Access_Denied  1: Read_Only  2: Edit  4: Full_Trust  -1: None ")
  public Integer getAccess() {
    return access;
  }

  public void setAccess(Integer access) {
    this.access = access;
  }

  public AttachmentDTO saveType(Integer saveType) {
    this.saveType = saveType;
    return this;
  }

   /**
   * Possible values:  0: File_System  1: Database 
   * @return saveType
  **/
  @ApiModelProperty(value = "Possible values:  0: File_System  1: Database ")
  public Integer getSaveType() {
    return saveType;
  }

  public void setSaveType(Integer saveType) {
    this.saveType = saveType;
  }

  public AttachmentDTO filesize(Long filesize) {
    this.filesize = filesize;
    return this;
  }

   /**
   * File Size
   * @return filesize
  **/
  @ApiModelProperty(value = "File Size")
  public Long getFilesize() {
    return filesize;
  }

  public void setFilesize(Long filesize) {
    this.filesize = filesize;
  }

  public AttachmentDTO kind(Integer kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Possible values:  0: ExternalAttachement  1: InternalAttachement 
   * @return kind
  **/
  @ApiModelProperty(value = "Possible values:  0: ExternalAttachement  1: InternalAttachement ")
  public Integer getKind() {
    return kind;
  }

  public void setKind(Integer kind) {
    this.kind = kind;
  }

  public AttachmentDTO attachedDocnumber(Integer attachedDocnumber) {
    this.attachedDocnumber = attachedDocnumber;
    return this;
  }

   /**
   * Document Identifier if the internal attachment
   * @return attachedDocnumber
  **/
  @ApiModelProperty(value = "Document Identifier if the internal attachment")
  public Integer getAttachedDocnumber() {
    return attachedDocnumber;
  }

  public void setAttachedDocnumber(Integer attachedDocnumber) {
    this.attachedDocnumber = attachedDocnumber;
  }

  public AttachmentDTO ixCheck(Boolean ixCheck) {
    this.ixCheck = ixCheck;
    return this;
  }

   /**
   * Send the file to IX service in the case of shipment
   * @return ixCheck
  **/
  @ApiModelProperty(value = "Send the file to IX service in the case of shipment")
  public Boolean isIxCheck() {
    return ixCheck;
  }

  public void setIxCheck(Boolean ixCheck) {
    this.ixCheck = ixCheck;
  }

  public AttachmentDTO attachmentRevision(Integer attachmentRevision) {
    this.attachmentRevision = attachmentRevision;
    return this;
  }

   /**
   * 
   * @return attachmentRevision
  **/
  @ApiModelProperty(value = "")
  public Integer getAttachmentRevision() {
    return attachmentRevision;
  }

  public void setAttachmentRevision(Integer attachmentRevision) {
    this.attachmentRevision = attachmentRevision;
  }

  public AttachmentDTO compressionMode(Integer compressionMode) {
    this.compressionMode = compressionMode;
    return this;
  }

   /**
   * Possible values:  0: None  1: CompressChilkat91  2: CompressChilkat95  3: CompressChilkat95AndCryptoAes256 
   * @return compressionMode
  **/
  @ApiModelProperty(value = "Possible values:  0: None  1: CompressChilkat91  2: CompressChilkat95  3: CompressChilkat95AndCryptoAes256 ")
  public Integer getCompressionMode() {
    return compressionMode;
  }

  public void setCompressionMode(Integer compressionMode) {
    this.compressionMode = compressionMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentDTO attachmentDTO = (AttachmentDTO) o;
    return Objects.equals(this.id, attachmentDTO.id) &&
        Objects.equals(this.docnumber, attachmentDTO.docnumber) &&
        Objects.equals(this.revision, attachmentDTO.revision) &&
        Objects.equals(this.filename, attachmentDTO.filename) &&
        Objects.equals(this.filepath, attachmentDTO.filepath) &&
        Objects.equals(this.originalname, attachmentDTO.originalname) &&
        Objects.equals(this.device, attachmentDTO.device) &&
        Objects.equals(this.cdlabel, attachmentDTO.cdlabel) &&
        Objects.equals(this.comment, attachmentDTO.comment) &&
        Objects.equals(this.importdate, attachmentDTO.importdate) &&
        Objects.equals(this.user, attachmentDTO.user) &&
        Objects.equals(this.userCompleteName, attachmentDTO.userCompleteName) &&
        Objects.equals(this.block, attachmentDTO.block) &&
        Objects.equals(this.compliantcopy, attachmentDTO.compliantcopy) &&
        Objects.equals(this.footprint, attachmentDTO.footprint) &&
        Objects.equals(this.checksend, attachmentDTO.checksend) &&
        Objects.equals(this.aosflag, attachmentDTO.aosflag) &&
        Objects.equals(this.access, attachmentDTO.access) &&
        Objects.equals(this.saveType, attachmentDTO.saveType) &&
        Objects.equals(this.filesize, attachmentDTO.filesize) &&
        Objects.equals(this.kind, attachmentDTO.kind) &&
        Objects.equals(this.attachedDocnumber, attachmentDTO.attachedDocnumber) &&
        Objects.equals(this.ixCheck, attachmentDTO.ixCheck) &&
        Objects.equals(this.attachmentRevision, attachmentDTO.attachmentRevision) &&
        Objects.equals(this.compressionMode, attachmentDTO.compressionMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, docnumber, revision, filename, filepath, originalname, device, cdlabel, comment, importdate, user, userCompleteName, block, compliantcopy, footprint, checksend, aosflag, access, saveType, filesize, kind, attachedDocnumber, ixCheck, attachmentRevision, compressionMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    docnumber: ").append(toIndentedString(docnumber)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    filepath: ").append(toIndentedString(filepath)).append("\n");
    sb.append("    originalname: ").append(toIndentedString(originalname)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    cdlabel: ").append(toIndentedString(cdlabel)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    importdate: ").append(toIndentedString(importdate)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userCompleteName: ").append(toIndentedString(userCompleteName)).append("\n");
    sb.append("    block: ").append(toIndentedString(block)).append("\n");
    sb.append("    compliantcopy: ").append(toIndentedString(compliantcopy)).append("\n");
    sb.append("    footprint: ").append(toIndentedString(footprint)).append("\n");
    sb.append("    checksend: ").append(toIndentedString(checksend)).append("\n");
    sb.append("    aosflag: ").append(toIndentedString(aosflag)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    saveType: ").append(toIndentedString(saveType)).append("\n");
    sb.append("    filesize: ").append(toIndentedString(filesize)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    attachedDocnumber: ").append(toIndentedString(attachedDocnumber)).append("\n");
    sb.append("    ixCheck: ").append(toIndentedString(ixCheck)).append("\n");
    sb.append("    attachmentRevision: ").append(toIndentedString(attachmentRevision)).append("\n");
    sb.append("    compressionMode: ").append(toIndentedString(compressionMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

