/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AssocitationFieldItem;
import io.swagger.client.model.AuthorityDataDTO;
import io.swagger.client.model.DependencyFieldItem;
import io.swagger.client.model.FieldBaseDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AuthorityDataFieldDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AuthorityDataFieldDTO extends FieldBaseDTO {
  @SerializedName("value")
  private List<AuthorityDataDTO> value = null;

  public AuthorityDataFieldDTO value(List<AuthorityDataDTO> value) {
    this.value = value;
    return this;
  }

  public AuthorityDataFieldDTO addValueItem(AuthorityDataDTO valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<AuthorityDataDTO>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public List<AuthorityDataDTO> getValue() {
    return value;
  }

  public void setValue(List<AuthorityDataDTO> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorityDataFieldDTO authorityDataFieldDTO = (AuthorityDataFieldDTO) o;
    return Objects.equals(this.value, authorityDataFieldDTO.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorityDataFieldDTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

