/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetWindowsLogonRedirectUri response
 */
@ApiModel(description = "GetWindowsLogonRedirectUri response")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class AuthenticationTokenResponseDTO {
  @SerializedName("redirectUri")
  private String redirectUri = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("errorDescription")
  private String errorDescription = null;

  public AuthenticationTokenResponseDTO redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Redirect uri to address the browser
   * @return redirectUri
  **/
  @ApiModelProperty(value = "Redirect uri to address the browser")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public AuthenticationTokenResponseDTO error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Error code
   * @return error
  **/
  @ApiModelProperty(value = "Error code")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public AuthenticationTokenResponseDTO errorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
    return this;
  }

   /**
   * Error desciption
   * @return errorDescription
  **/
  @ApiModelProperty(value = "Error desciption")
  public String getErrorDescription() {
    return errorDescription;
  }

  public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationTokenResponseDTO authenticationTokenResponseDTO = (AuthenticationTokenResponseDTO) o;
    return Objects.equals(this.redirectUri, authenticationTokenResponseDTO.redirectUri) &&
        Objects.equals(this.error, authenticationTokenResponseDTO.error) &&
        Objects.equals(this.errorDescription, authenticationTokenResponseDTO.errorDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirectUri, error, errorDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationTokenResponseDTO {\n");
    
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

