/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of the Contact item
 */
@ApiModel(description = "Class of the Contact item")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class ContactDTO {
  @SerializedName("addressBookId")
  private Integer addressBookId = null;

  @SerializedName("contactName")
  private String contactName = null;

  @SerializedName("job")
  private String job = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("fax")
  private String fax = null;

  @SerializedName("cellPhone")
  private String cellPhone = null;

  @SerializedName("house")
  private String house = null;

  @SerializedName("department")
  private String department = null;

  @SerializedName("office")
  private String office = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("id")
  private Integer id = null;

  public ContactDTO addressBookId(Integer addressBookId) {
    this.addressBookId = addressBookId;
    return this;
  }

   /**
   * Identifier of Address Book
   * @return addressBookId
  **/
  @ApiModelProperty(value = "Identifier of Address Book")
  public Integer getAddressBookId() {
    return addressBookId;
  }

  public void setAddressBookId(Integer addressBookId) {
    this.addressBookId = addressBookId;
  }

  public ContactDTO contactName(String contactName) {
    this.contactName = contactName;
    return this;
  }

   /**
   * Name
   * @return contactName
  **/
  @ApiModelProperty(value = "Name")
  public String getContactName() {
    return contactName;
  }

  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  public ContactDTO job(String job) {
    this.job = job;
    return this;
  }

   /**
   * Job
   * @return job
  **/
  @ApiModelProperty(value = "Job")
  public String getJob() {
    return job;
  }

  public void setJob(String job) {
    this.job = job;
  }

  public ContactDTO phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Phone Number
   * @return phone
  **/
  @ApiModelProperty(value = "Phone Number")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public ContactDTO fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Fax Number
   * @return fax
  **/
  @ApiModelProperty(value = "Fax Number")
  public String getFax() {
    return fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public ContactDTO cellPhone(String cellPhone) {
    this.cellPhone = cellPhone;
    return this;
  }

   /**
   * Mobile Phone Number
   * @return cellPhone
  **/
  @ApiModelProperty(value = "Mobile Phone Number")
  public String getCellPhone() {
    return cellPhone;
  }

  public void setCellPhone(String cellPhone) {
    this.cellPhone = cellPhone;
  }

  public ContactDTO house(String house) {
    this.house = house;
    return this;
  }

   /**
   * Address
   * @return house
  **/
  @ApiModelProperty(value = "Address")
  public String getHouse() {
    return house;
  }

  public void setHouse(String house) {
    this.house = house;
  }

  public ContactDTO department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Department
   * @return department
  **/
  @ApiModelProperty(value = "Department")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public ContactDTO office(String office) {
    this.office = office;
    return this;
  }

   /**
   * Office
   * @return office
  **/
  @ApiModelProperty(value = "Office")
  public String getOffice() {
    return office;
  }

  public void setOffice(String office) {
    this.office = office;
  }

  public ContactDTO email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email
   * @return email
  **/
  @ApiModelProperty(value = "Email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ContactDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier
   * @return id
  **/
  @ApiModelProperty(value = "Identifier")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactDTO contactDTO = (ContactDTO) o;
    return Objects.equals(this.addressBookId, contactDTO.addressBookId) &&
        Objects.equals(this.contactName, contactDTO.contactName) &&
        Objects.equals(this.job, contactDTO.job) &&
        Objects.equals(this.phone, contactDTO.phone) &&
        Objects.equals(this.fax, contactDTO.fax) &&
        Objects.equals(this.cellPhone, contactDTO.cellPhone) &&
        Objects.equals(this.house, contactDTO.house) &&
        Objects.equals(this.department, contactDTO.department) &&
        Objects.equals(this.office, contactDTO.office) &&
        Objects.equals(this.email, contactDTO.email) &&
        Objects.equals(this.id, contactDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressBookId, contactName, job, phone, fax, cellPhone, house, department, office, email, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactDTO {\n");
    
    sb.append("    addressBookId: ").append(toIndentedString(addressBookId)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    cellPhone: ").append(toIndentedString(cellPhone)).append("\n");
    sb.append("    house: ").append(toIndentedString(house)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    office: ").append(toIndentedString(office)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

