/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * Class of optical character recognition (OCR) on a document profile.
 */
@ApiModel(description = "Class of optical character recognition (OCR) on a document profile.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class DocToOcrDTO {
  @SerializedName("docnumber")
  private Integer docnumber = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("revision")
  private Integer revision = null;

  @SerializedName("ocrDate")
  private DateTime ocrDate = null;

  @SerializedName("user")
  private Integer user = null;

  @SerializedName("guid")
  private String guid = null;

  @SerializedName("numAttemps")
  private Integer numAttemps = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  public DocToOcrDTO docnumber(Integer docnumber) {
    this.docnumber = docnumber;
    return this;
  }

   /**
   * Document Identifier
   * @return docnumber
  **/
  @ApiModelProperty(value = "Document Identifier")
  public Integer getDocnumber() {
    return docnumber;
  }

  public void setDocnumber(Integer docnumber) {
    this.docnumber = docnumber;
  }

  public DocToOcrDTO status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Possible values:  1: Pending  2: Failed  3: Scheduled  4: Pending_Rev  5: Failed_Rev  6: Scheduled_Rev 
   * @return status
  **/
  @ApiModelProperty(value = "Possible values:  1: Pending  2: Failed  3: Scheduled  4: Pending_Rev  5: Failed_Rev  6: Scheduled_Rev ")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public DocToOcrDTO revision(Integer revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Revision of document
   * @return revision
  **/
  @ApiModelProperty(value = "Revision of document")
  public Integer getRevision() {
    return revision;
  }

  public void setRevision(Integer revision) {
    this.revision = revision;
  }

  public DocToOcrDTO ocrDate(DateTime ocrDate) {
    this.ocrDate = ocrDate;
    return this;
  }

   /**
   * Schedule Date
   * @return ocrDate
  **/
  @ApiModelProperty(value = "Schedule Date")
  public DateTime getOcrDate() {
    return ocrDate;
  }

  public void setOcrDate(DateTime ocrDate) {
    this.ocrDate = ocrDate;
  }

  public DocToOcrDTO user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * User Identifier
   * @return user
  **/
  @ApiModelProperty(value = "User Identifier")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public DocToOcrDTO guid(String guid) {
    this.guid = guid;
    return this;
  }

   /**
   * Identifier
   * @return guid
  **/
  @ApiModelProperty(value = "Identifier")
  public String getGuid() {
    return guid;
  }

  public void setGuid(String guid) {
    this.guid = guid;
  }

  public DocToOcrDTO numAttemps(Integer numAttemps) {
    this.numAttemps = numAttemps;
    return this;
  }

   /**
   * Number of Attempts
   * @return numAttemps
  **/
  @ApiModelProperty(value = "Number of Attempts")
  public Integer getNumAttemps() {
    return numAttemps;
  }

  public void setNumAttemps(Integer numAttemps) {
    this.numAttemps = numAttemps;
  }

  public DocToOcrDTO errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Error Message
   * @return errorMessage
  **/
  @ApiModelProperty(value = "Error Message")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocToOcrDTO docToOcrDTO = (DocToOcrDTO) o;
    return Objects.equals(this.docnumber, docToOcrDTO.docnumber) &&
        Objects.equals(this.status, docToOcrDTO.status) &&
        Objects.equals(this.revision, docToOcrDTO.revision) &&
        Objects.equals(this.ocrDate, docToOcrDTO.ocrDate) &&
        Objects.equals(this.user, docToOcrDTO.user) &&
        Objects.equals(this.guid, docToOcrDTO.guid) &&
        Objects.equals(this.numAttemps, docToOcrDTO.numAttemps) &&
        Objects.equals(this.errorMessage, docToOcrDTO.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docnumber, status, revision, ocrDate, user, guid, numAttemps, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocToOcrDTO {\n");
    
    sb.append("    docnumber: ").append(toIndentedString(docnumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    ocrDate: ").append(toIndentedString(ocrDate)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    numAttemps: ").append(toIndentedString(numAttemps)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

