/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of options for editing profile
 */
@ApiModel(description = "Class of options for editing profile")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class EditProfileOptionsDTO {
  @SerializedName("canLoadPredefinedProfile")
  private Boolean canLoadPredefinedProfile = null;

  @SerializedName("canUnlockProfile")
  private Boolean canUnlockProfile = null;

  @SerializedName("canUnlockProfileMessage")
  private String canUnlockProfileMessage = null;

  @SerializedName("canSwitch")
  private Boolean canSwitch = null;

  @SerializedName("allowEditPaFields")
  private Boolean allowEditPaFields = null;

  @SerializedName("workflowSubjected")
  private Boolean workflowSubjected = null;

  public EditProfileOptionsDTO canLoadPredefinedProfile(Boolean canLoadPredefinedProfile) {
    this.canLoadPredefinedProfile = canLoadPredefinedProfile;
    return this;
  }

   /**
   * Load Predefined Profile
   * @return canLoadPredefinedProfile
  **/
  @ApiModelProperty(value = "Load Predefined Profile")
  public Boolean isCanLoadPredefinedProfile() {
    return canLoadPredefinedProfile;
  }

  public void setCanLoadPredefinedProfile(Boolean canLoadPredefinedProfile) {
    this.canLoadPredefinedProfile = canLoadPredefinedProfile;
  }

  public EditProfileOptionsDTO canUnlockProfile(Boolean canUnlockProfile) {
    this.canUnlockProfile = canUnlockProfile;
    return this;
  }

   /**
   * Unlock Profile
   * @return canUnlockProfile
  **/
  @ApiModelProperty(value = "Unlock Profile")
  public Boolean isCanUnlockProfile() {
    return canUnlockProfile;
  }

  public void setCanUnlockProfile(Boolean canUnlockProfile) {
    this.canUnlockProfile = canUnlockProfile;
  }

  public EditProfileOptionsDTO canUnlockProfileMessage(String canUnlockProfileMessage) {
    this.canUnlockProfileMessage = canUnlockProfileMessage;
    return this;
  }

   /**
   * Unlock Profile Message
   * @return canUnlockProfileMessage
  **/
  @ApiModelProperty(value = "Unlock Profile Message")
  public String getCanUnlockProfileMessage() {
    return canUnlockProfileMessage;
  }

  public void setCanUnlockProfileMessage(String canUnlockProfileMessage) {
    this.canUnlockProfileMessage = canUnlockProfileMessage;
  }

  public EditProfileOptionsDTO canSwitch(Boolean canSwitch) {
    this.canSwitch = canSwitch;
    return this;
  }

   /**
   * Enabled Switch
   * @return canSwitch
  **/
  @ApiModelProperty(value = "Enabled Switch")
  public Boolean isCanSwitch() {
    return canSwitch;
  }

  public void setCanSwitch(Boolean canSwitch) {
    this.canSwitch = canSwitch;
  }

  public EditProfileOptionsDTO allowEditPaFields(Boolean allowEditPaFields) {
    this.allowEditPaFields = allowEditPaFields;
    return this;
  }

   /**
   * Editing fields of Public Amministration (PA) information
   * @return allowEditPaFields
  **/
  @ApiModelProperty(value = "Editing fields of Public Amministration (PA) information")
  public Boolean isAllowEditPaFields() {
    return allowEditPaFields;
  }

  public void setAllowEditPaFields(Boolean allowEditPaFields) {
    this.allowEditPaFields = allowEditPaFields;
  }

  public EditProfileOptionsDTO workflowSubjected(Boolean workflowSubjected) {
    this.workflowSubjected = workflowSubjected;
    return this;
  }

   /**
   * Workflow in progress
   * @return workflowSubjected
  **/
  @ApiModelProperty(value = "Workflow in progress")
  public Boolean isWorkflowSubjected() {
    return workflowSubjected;
  }

  public void setWorkflowSubjected(Boolean workflowSubjected) {
    this.workflowSubjected = workflowSubjected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditProfileOptionsDTO editProfileOptionsDTO = (EditProfileOptionsDTO) o;
    return Objects.equals(this.canLoadPredefinedProfile, editProfileOptionsDTO.canLoadPredefinedProfile) &&
        Objects.equals(this.canUnlockProfile, editProfileOptionsDTO.canUnlockProfile) &&
        Objects.equals(this.canUnlockProfileMessage, editProfileOptionsDTO.canUnlockProfileMessage) &&
        Objects.equals(this.canSwitch, editProfileOptionsDTO.canSwitch) &&
        Objects.equals(this.allowEditPaFields, editProfileOptionsDTO.allowEditPaFields) &&
        Objects.equals(this.workflowSubjected, editProfileOptionsDTO.workflowSubjected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canLoadPredefinedProfile, canUnlockProfile, canUnlockProfileMessage, canSwitch, allowEditPaFields, workflowSubjected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditProfileOptionsDTO {\n");
    
    sb.append("    canLoadPredefinedProfile: ").append(toIndentedString(canLoadPredefinedProfile)).append("\n");
    sb.append("    canUnlockProfile: ").append(toIndentedString(canUnlockProfile)).append("\n");
    sb.append("    canUnlockProfileMessage: ").append(toIndentedString(canUnlockProfileMessage)).append("\n");
    sb.append("    canSwitch: ").append(toIndentedString(canSwitch)).append("\n");
    sb.append("    allowEditPaFields: ").append(toIndentedString(allowEditPaFields)).append("\n");
    sb.append("    workflowSubjected: ").append(toIndentedString(workflowSubjected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

