/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SearchDTO;
import java.io.IOException;

/**
 * Class of criteria fields to calculate formula
 */
@ApiModel(description = "Class of criteria fields to calculate formula")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class FieldFormulaCalculateCriteriaDto {
  @SerializedName("searchFilterDto")
  private SearchDTO searchFilterDto = null;

  @SerializedName("fieldName")
  private String fieldName = null;

  @SerializedName("formula")
  private String formula = null;

  public FieldFormulaCalculateCriteriaDto searchFilterDto(SearchDTO searchFilterDto) {
    this.searchFilterDto = searchFilterDto;
    return this;
  }

   /**
   * Filter for search
   * @return searchFilterDto
  **/
  @ApiModelProperty(value = "Filter for search")
  public SearchDTO getSearchFilterDto() {
    return searchFilterDto;
  }

  public void setSearchFilterDto(SearchDTO searchFilterDto) {
    this.searchFilterDto = searchFilterDto;
  }

  public FieldFormulaCalculateCriteriaDto fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Field Name
   * @return fieldName
  **/
  @ApiModelProperty(value = "Field Name")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public FieldFormulaCalculateCriteriaDto formula(String formula) {
    this.formula = formula;
    return this;
  }

   /**
   * Formula
   * @return formula
  **/
  @ApiModelProperty(value = "Formula")
  public String getFormula() {
    return formula;
  }

  public void setFormula(String formula) {
    this.formula = formula;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldFormulaCalculateCriteriaDto fieldFormulaCalculateCriteriaDto = (FieldFormulaCalculateCriteriaDto) o;
    return Objects.equals(this.searchFilterDto, fieldFormulaCalculateCriteriaDto.searchFilterDto) &&
        Objects.equals(this.fieldName, fieldFormulaCalculateCriteriaDto.fieldName) &&
        Objects.equals(this.formula, fieldFormulaCalculateCriteriaDto.formula);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchFilterDto, fieldName, formula);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldFormulaCalculateCriteriaDto {\n");
    
    sb.append("    searchFilterDto: ").append(toIndentedString(searchFilterDto)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    formula: ").append(toIndentedString(formula)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

