/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MaskClassOptionsDTO;
import io.swagger.client.model.MaskDetailDTO;
import io.swagger.client.model.PredefinedProfileDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Class of mask to archive documents
 */
@ApiModel(description = "Class of mask to archive documents")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class MaskDTO {
  @SerializedName("id")
  private String id = null;

  @SerializedName("maskName")
  private String maskName = null;

  @SerializedName("maskDescription")
  private String maskDescription = null;

  @SerializedName("predefinedProfileId")
  private Integer predefinedProfileId = null;

  @SerializedName("user")
  private Integer user = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("isRoot")
  private Boolean isRoot = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("paMode")
  private Integer paMode = null;

  @SerializedName("showAdditional")
  private Boolean showAdditional = null;

  @SerializedName("kind")
  private Integer kind = null;

  @SerializedName("showGroups")
  private Boolean showGroups = null;

  @SerializedName("userCompleteName")
  private String userCompleteName = null;

  @SerializedName("predefinedProfile")
  private PredefinedProfileDTO predefinedProfile = null;

  @SerializedName("maskDetails")
  private List<MaskDetailDTO> maskDetails = null;

  @SerializedName("maskClassOptions")
  private List<MaskClassOptionsDTO> maskClassOptions = null;

  public MaskDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier
   * @return id
  **/
  @ApiModelProperty(value = "Identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MaskDTO maskName(String maskName) {
    this.maskName = maskName;
    return this;
  }

   /**
   * Name
   * @return maskName
  **/
  @ApiModelProperty(value = "Name")
  public String getMaskName() {
    return maskName;
  }

  public void setMaskName(String maskName) {
    this.maskName = maskName;
  }

  public MaskDTO maskDescription(String maskDescription) {
    this.maskDescription = maskDescription;
    return this;
  }

   /**
   * Description
   * @return maskDescription
  **/
  @ApiModelProperty(value = "Description")
  public String getMaskDescription() {
    return maskDescription;
  }

  public void setMaskDescription(String maskDescription) {
    this.maskDescription = maskDescription;
  }

  public MaskDTO predefinedProfileId(Integer predefinedProfileId) {
    this.predefinedProfileId = predefinedProfileId;
    return this;
  }

   /**
   * Predefined Profile Identifier
   * @return predefinedProfileId
  **/
  @ApiModelProperty(value = "Predefined Profile Identifier")
  public Integer getPredefinedProfileId() {
    return predefinedProfileId;
  }

  public void setPredefinedProfileId(Integer predefinedProfileId) {
    this.predefinedProfileId = predefinedProfileId;
  }

  public MaskDTO user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * Author Identifier
   * @return user
  **/
  @ApiModelProperty(value = "Author Identifier")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public MaskDTO externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * External Identifier
   * @return externalId
  **/
  @ApiModelProperty(value = "External Identifier")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public MaskDTO isRoot(Boolean isRoot) {
    this.isRoot = isRoot;
    return this;
  }

   /**
   * Root
   * @return isRoot
  **/
  @ApiModelProperty(value = "Root")
  public Boolean isIsRoot() {
    return isRoot;
  }

  public void setIsRoot(Boolean isRoot) {
    this.isRoot = isRoot;
  }

  public MaskDTO type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Possible values:  0: Nothing  1: Barcode  2: Archiviazione 
   * @return type
  **/
  @ApiModelProperty(value = "Possible values:  0: Nothing  1: Barcode  2: Archiviazione ")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public MaskDTO paMode(Integer paMode) {
    this.paMode = paMode;
    return this;
  }

   /**
   * Possible values:  0: None  1: OnlyNever  2: OnlyOptionally  3: NeverOrOptionally  4: OnlyAlways  5: AlwaysOrNever  6: AlwaysOrOptionally  7: All 
   * @return paMode
  **/
  @ApiModelProperty(value = "Possible values:  0: None  1: OnlyNever  2: OnlyOptionally  3: NeverOrOptionally  4: OnlyAlways  5: AlwaysOrNever  6: AlwaysOrOptionally  7: All ")
  public Integer getPaMode() {
    return paMode;
  }

  public void setPaMode(Integer paMode) {
    this.paMode = paMode;
  }

  public MaskDTO showAdditional(Boolean showAdditional) {
    this.showAdditional = showAdditional;
    return this;
  }

   /**
   * Show Additional
   * @return showAdditional
  **/
  @ApiModelProperty(value = "Show Additional")
  public Boolean isShowAdditional() {
    return showAdditional;
  }

  public void setShowAdditional(Boolean showAdditional) {
    this.showAdditional = showAdditional;
  }

  public MaskDTO kind(Integer kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Possible values:  0: UserMask  1: SystemMask 
   * @return kind
  **/
  @ApiModelProperty(value = "Possible values:  0: UserMask  1: SystemMask ")
  public Integer getKind() {
    return kind;
  }

  public void setKind(Integer kind) {
    this.kind = kind;
  }

  public MaskDTO showGroups(Boolean showGroups) {
    this.showGroups = showGroups;
    return this;
  }

   /**
   * Show Groups
   * @return showGroups
  **/
  @ApiModelProperty(value = "Show Groups")
  public Boolean isShowGroups() {
    return showGroups;
  }

  public void setShowGroups(Boolean showGroups) {
    this.showGroups = showGroups;
  }

  public MaskDTO userCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
    return this;
  }

   /**
   * Author Complete Name
   * @return userCompleteName
  **/
  @ApiModelProperty(value = "Author Complete Name")
  public String getUserCompleteName() {
    return userCompleteName;
  }

  public void setUserCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
  }

  public MaskDTO predefinedProfile(PredefinedProfileDTO predefinedProfile) {
    this.predefinedProfile = predefinedProfile;
    return this;
  }

   /**
   * Predefined Profile associated with the mask
   * @return predefinedProfile
  **/
  @ApiModelProperty(value = "Predefined Profile associated with the mask")
  public PredefinedProfileDTO getPredefinedProfile() {
    return predefinedProfile;
  }

  public void setPredefinedProfile(PredefinedProfileDTO predefinedProfile) {
    this.predefinedProfile = predefinedProfile;
  }

  public MaskDTO maskDetails(List<MaskDetailDTO> maskDetails) {
    this.maskDetails = maskDetails;
    return this;
  }

  public MaskDTO addMaskDetailsItem(MaskDetailDTO maskDetailsItem) {
    if (this.maskDetails == null) {
      this.maskDetails = new ArrayList<MaskDetailDTO>();
    }
    this.maskDetails.add(maskDetailsItem);
    return this;
  }

   /**
   * Details
   * @return maskDetails
  **/
  @ApiModelProperty(value = "Details")
  public List<MaskDetailDTO> getMaskDetails() {
    return maskDetails;
  }

  public void setMaskDetails(List<MaskDetailDTO> maskDetails) {
    this.maskDetails = maskDetails;
  }

  public MaskDTO maskClassOptions(List<MaskClassOptionsDTO> maskClassOptions) {
    this.maskClassOptions = maskClassOptions;
    return this;
  }

  public MaskDTO addMaskClassOptionsItem(MaskClassOptionsDTO maskClassOptionsItem) {
    if (this.maskClassOptions == null) {
      this.maskClassOptions = new ArrayList<MaskClassOptionsDTO>();
    }
    this.maskClassOptions.add(maskClassOptionsItem);
    return this;
  }

   /**
   * Options on document type
   * @return maskClassOptions
  **/
  @ApiModelProperty(value = "Options on document type")
  public List<MaskClassOptionsDTO> getMaskClassOptions() {
    return maskClassOptions;
  }

  public void setMaskClassOptions(List<MaskClassOptionsDTO> maskClassOptions) {
    this.maskClassOptions = maskClassOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaskDTO maskDTO = (MaskDTO) o;
    return Objects.equals(this.id, maskDTO.id) &&
        Objects.equals(this.maskName, maskDTO.maskName) &&
        Objects.equals(this.maskDescription, maskDTO.maskDescription) &&
        Objects.equals(this.predefinedProfileId, maskDTO.predefinedProfileId) &&
        Objects.equals(this.user, maskDTO.user) &&
        Objects.equals(this.externalId, maskDTO.externalId) &&
        Objects.equals(this.isRoot, maskDTO.isRoot) &&
        Objects.equals(this.type, maskDTO.type) &&
        Objects.equals(this.paMode, maskDTO.paMode) &&
        Objects.equals(this.showAdditional, maskDTO.showAdditional) &&
        Objects.equals(this.kind, maskDTO.kind) &&
        Objects.equals(this.showGroups, maskDTO.showGroups) &&
        Objects.equals(this.userCompleteName, maskDTO.userCompleteName) &&
        Objects.equals(this.predefinedProfile, maskDTO.predefinedProfile) &&
        Objects.equals(this.maskDetails, maskDTO.maskDetails) &&
        Objects.equals(this.maskClassOptions, maskDTO.maskClassOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, maskName, maskDescription, predefinedProfileId, user, externalId, isRoot, type, paMode, showAdditional, kind, showGroups, userCompleteName, predefinedProfile, maskDetails, maskClassOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaskDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maskName: ").append(toIndentedString(maskName)).append("\n");
    sb.append("    maskDescription: ").append(toIndentedString(maskDescription)).append("\n");
    sb.append("    predefinedProfileId: ").append(toIndentedString(predefinedProfileId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    isRoot: ").append(toIndentedString(isRoot)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    paMode: ").append(toIndentedString(paMode)).append("\n");
    sb.append("    showAdditional: ").append(toIndentedString(showAdditional)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    showGroups: ").append(toIndentedString(showGroups)).append("\n");
    sb.append("    userCompleteName: ").append(toIndentedString(userCompleteName)).append("\n");
    sb.append("    predefinedProfile: ").append(toIndentedString(predefinedProfile)).append("\n");
    sb.append("    maskDetails: ").append(toIndentedString(maskDetails)).append("\n");
    sb.append("    maskClassOptions: ").append(toIndentedString(maskClassOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

