/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * Class of profile desktop information
 */
@ApiModel(description = "Class of profile desktop information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class ProfileForDesktopDTO {
  @SerializedName("revision")
  private Integer revision = null;

  @SerializedName("docNumber")
  private Integer docNumber = null;

  @SerializedName("number")
  private String number = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("documentDate")
  private DateTime documentDate = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("from")
  private String from = null;

  @SerializedName("fileName")
  private String fileName = null;

  public ProfileForDesktopDTO revision(Integer revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Revision
   * @return revision
  **/
  @ApiModelProperty(value = "Revision")
  public Integer getRevision() {
    return revision;
  }

  public void setRevision(Integer revision) {
    this.revision = revision;
  }

  public ProfileForDesktopDTO docNumber(Integer docNumber) {
    this.docNumber = docNumber;
    return this;
  }

   /**
   * Document Identifier
   * @return docNumber
  **/
  @ApiModelProperty(value = "Document Identifier")
  public Integer getDocNumber() {
    return docNumber;
  }

  public void setDocNumber(Integer docNumber) {
    this.docNumber = docNumber;
  }

  public ProfileForDesktopDTO number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Internal Protocol
   * @return number
  **/
  @ApiModelProperty(value = "Internal Protocol")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public ProfileForDesktopDTO subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Subject
   * @return subject
  **/
  @ApiModelProperty(value = "Subject")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public ProfileForDesktopDTO documentDate(DateTime documentDate) {
    this.documentDate = documentDate;
    return this;
  }

   /**
   * Date of document
   * @return documentDate
  **/
  @ApiModelProperty(value = "Date of document")
  public DateTime getDocumentDate() {
    return documentDate;
  }

  public void setDocumentDate(DateTime documentDate) {
    this.documentDate = documentDate;
  }

  public ProfileForDesktopDTO to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Reciviers
   * @return to
  **/
  @ApiModelProperty(value = "Reciviers")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public ProfileForDesktopDTO from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Sender
   * @return from
  **/
  @ApiModelProperty(value = "Sender")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public ProfileForDesktopDTO fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * File name associated with the profile
   * @return fileName
  **/
  @ApiModelProperty(value = "File name associated with the profile")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileForDesktopDTO profileForDesktopDTO = (ProfileForDesktopDTO) o;
    return Objects.equals(this.revision, profileForDesktopDTO.revision) &&
        Objects.equals(this.docNumber, profileForDesktopDTO.docNumber) &&
        Objects.equals(this.number, profileForDesktopDTO.number) &&
        Objects.equals(this.subject, profileForDesktopDTO.subject) &&
        Objects.equals(this.documentDate, profileForDesktopDTO.documentDate) &&
        Objects.equals(this.to, profileForDesktopDTO.to) &&
        Objects.equals(this.from, profileForDesktopDTO.from) &&
        Objects.equals(this.fileName, profileForDesktopDTO.fileName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(revision, docNumber, number, subject, documentDate, to, from, fileName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileForDesktopDTO {\n");
    
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    docNumber: ").append(toIndentedString(docNumber)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    documentDate: ").append(toIndentedString(documentDate)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

