/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FieldBaseDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Class of preview group for documents
 */
@ApiModel(description = "Class of preview group for documents")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class ProfilePreviewGroupDTO {
  @SerializedName("labelGroup")
  private String labelGroup = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("order")
  private Integer order = null;

  @SerializedName("fields")
  private List<FieldBaseDTO> fields = null;

  @SerializedName("groupType")
  private Integer groupType = null;

  public ProfilePreviewGroupDTO labelGroup(String labelGroup) {
    this.labelGroup = labelGroup;
    return this;
  }

   /**
   * Label of Group
   * @return labelGroup
  **/
  @ApiModelProperty(value = "Label of Group")
  public String getLabelGroup() {
    return labelGroup;
  }

  public void setLabelGroup(String labelGroup) {
    this.labelGroup = labelGroup;
  }

  public ProfilePreviewGroupDTO label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Label
   * @return label
  **/
  @ApiModelProperty(value = "Label")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ProfilePreviewGroupDTO order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Order
   * @return order
  **/
  @ApiModelProperty(value = "Order")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public ProfilePreviewGroupDTO fields(List<FieldBaseDTO> fields) {
    this.fields = fields;
    return this;
  }

  public ProfilePreviewGroupDTO addFieldsItem(FieldBaseDTO fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<FieldBaseDTO>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * List of Fields
   * @return fields
  **/
  @ApiModelProperty(value = "List of Fields")
  public List<FieldBaseDTO> getFields() {
    return fields;
  }

  public void setFields(List<FieldBaseDTO> fields) {
    this.fields = fields;
  }

  public ProfilePreviewGroupDTO groupType(Integer groupType) {
    this.groupType = groupType;
    return this;
  }

   /**
   * Possible values:  0: Standard  1: From  2: To  3: CC  4: Senders  5: Additionals  6: Notes  7: InternalAttachments  8: ExternalAttachments  9: Folders  10: Binders  11: Associations 
   * @return groupType
  **/
  @ApiModelProperty(value = "Possible values:  0: Standard  1: From  2: To  3: CC  4: Senders  5: Additionals  6: Notes  7: InternalAttachments  8: ExternalAttachments  9: Folders  10: Binders  11: Associations ")
  public Integer getGroupType() {
    return groupType;
  }

  public void setGroupType(Integer groupType) {
    this.groupType = groupType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfilePreviewGroupDTO profilePreviewGroupDTO = (ProfilePreviewGroupDTO) o;
    return Objects.equals(this.labelGroup, profilePreviewGroupDTO.labelGroup) &&
        Objects.equals(this.label, profilePreviewGroupDTO.label) &&
        Objects.equals(this.order, profilePreviewGroupDTO.order) &&
        Objects.equals(this.fields, profilePreviewGroupDTO.fields) &&
        Objects.equals(this.groupType, profilePreviewGroupDTO.groupType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelGroup, label, order, fields, groupType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfilePreviewGroupDTO {\n");
    
    sb.append("    labelGroup: ").append(toIndentedString(labelGroup)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    groupType: ").append(toIndentedString(groupType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

