/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of status for queue aggregation
 */
@ApiModel(description = "Class of status for queue aggregation")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class QueueStateAggregationInfoDto {
  @SerializedName("awaiting")
  private Integer awaiting = null;

  @SerializedName("enqueued")
  private Integer enqueued = null;

  @SerializedName("processing")
  private Integer processing = null;

  @SerializedName("scheduled")
  private Integer scheduled = null;

  @SerializedName("failed")
  private Integer failed = null;

  @SerializedName("succededOk")
  private Integer succededOk = null;

  @SerializedName("succededKo")
  private Integer succededKo = null;

  @SerializedName("deleted")
  private Integer deleted = null;

  public QueueStateAggregationInfoDto awaiting(Integer awaiting) {
    this.awaiting = awaiting;
    return this;
  }

   /**
   * Wainting
   * @return awaiting
  **/
  @ApiModelProperty(value = "Wainting")
  public Integer getAwaiting() {
    return awaiting;
  }

  public void setAwaiting(Integer awaiting) {
    this.awaiting = awaiting;
  }

  public QueueStateAggregationInfoDto enqueued(Integer enqueued) {
    this.enqueued = enqueued;
    return this;
  }

   /**
   * Enqueued
   * @return enqueued
  **/
  @ApiModelProperty(value = "Enqueued")
  public Integer getEnqueued() {
    return enqueued;
  }

  public void setEnqueued(Integer enqueued) {
    this.enqueued = enqueued;
  }

  public QueueStateAggregationInfoDto processing(Integer processing) {
    this.processing = processing;
    return this;
  }

   /**
   * Processing
   * @return processing
  **/
  @ApiModelProperty(value = "Processing")
  public Integer getProcessing() {
    return processing;
  }

  public void setProcessing(Integer processing) {
    this.processing = processing;
  }

  public QueueStateAggregationInfoDto scheduled(Integer scheduled) {
    this.scheduled = scheduled;
    return this;
  }

   /**
   * Scheduled
   * @return scheduled
  **/
  @ApiModelProperty(value = "Scheduled")
  public Integer getScheduled() {
    return scheduled;
  }

  public void setScheduled(Integer scheduled) {
    this.scheduled = scheduled;
  }

  public QueueStateAggregationInfoDto failed(Integer failed) {
    this.failed = failed;
    return this;
  }

   /**
   * Failed
   * @return failed
  **/
  @ApiModelProperty(value = "Failed")
  public Integer getFailed() {
    return failed;
  }

  public void setFailed(Integer failed) {
    this.failed = failed;
  }

  public QueueStateAggregationInfoDto succededOk(Integer succededOk) {
    this.succededOk = succededOk;
    return this;
  }

   /**
   * Successful
   * @return succededOk
  **/
  @ApiModelProperty(value = "Successful")
  public Integer getSuccededOk() {
    return succededOk;
  }

  public void setSuccededOk(Integer succededOk) {
    this.succededOk = succededOk;
  }

  public QueueStateAggregationInfoDto succededKo(Integer succededKo) {
    this.succededKo = succededKo;
    return this;
  }

   /**
   * Unsuccessful
   * @return succededKo
  **/
  @ApiModelProperty(value = "Unsuccessful")
  public Integer getSuccededKo() {
    return succededKo;
  }

  public void setSuccededKo(Integer succededKo) {
    this.succededKo = succededKo;
  }

  public QueueStateAggregationInfoDto deleted(Integer deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "Deleted")
  public Integer getDeleted() {
    return deleted;
  }

  public void setDeleted(Integer deleted) {
    this.deleted = deleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueStateAggregationInfoDto queueStateAggregationInfoDto = (QueueStateAggregationInfoDto) o;
    return Objects.equals(this.awaiting, queueStateAggregationInfoDto.awaiting) &&
        Objects.equals(this.enqueued, queueStateAggregationInfoDto.enqueued) &&
        Objects.equals(this.processing, queueStateAggregationInfoDto.processing) &&
        Objects.equals(this.scheduled, queueStateAggregationInfoDto.scheduled) &&
        Objects.equals(this.failed, queueStateAggregationInfoDto.failed) &&
        Objects.equals(this.succededOk, queueStateAggregationInfoDto.succededOk) &&
        Objects.equals(this.succededKo, queueStateAggregationInfoDto.succededKo) &&
        Objects.equals(this.deleted, queueStateAggregationInfoDto.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awaiting, enqueued, processing, scheduled, failed, succededOk, succededKo, deleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueStateAggregationInfoDto {\n");
    
    sb.append("    awaiting: ").append(toIndentedString(awaiting)).append("\n");
    sb.append("    enqueued: ").append(toIndentedString(enqueued)).append("\n");
    sb.append("    processing: ").append(toIndentedString(processing)).append("\n");
    sb.append("    scheduled: ").append(toIndentedString(scheduled)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    succededOk: ").append(toIndentedString(succededOk)).append("\n");
    sb.append("    succededKo: ").append(toIndentedString(succededKo)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

