/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SearchDTO;
import io.swagger.client.model.SelectDTO;
import java.io.IOException;

/**
 * SearchCriteriaDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class SearchCriteriaDto {
  @SerializedName("searchFilterDto")
  private SearchDTO searchFilterDto = null;

  @SerializedName("selectFilterDto")
  private SelectDTO selectFilterDto = null;

  public SearchCriteriaDto searchFilterDto(SearchDTO searchFilterDto) {
    this.searchFilterDto = searchFilterDto;
    return this;
  }

   /**
   * Get searchFilterDto
   * @return searchFilterDto
  **/
  @ApiModelProperty(value = "")
  public SearchDTO getSearchFilterDto() {
    return searchFilterDto;
  }

  public void setSearchFilterDto(SearchDTO searchFilterDto) {
    this.searchFilterDto = searchFilterDto;
  }

  public SearchCriteriaDto selectFilterDto(SelectDTO selectFilterDto) {
    this.selectFilterDto = selectFilterDto;
    return this;
  }

   /**
   * Get selectFilterDto
   * @return selectFilterDto
  **/
  @ApiModelProperty(value = "")
  public SelectDTO getSelectFilterDto() {
    return selectFilterDto;
  }

  public void setSelectFilterDto(SelectDTO selectFilterDto) {
    this.selectFilterDto = selectFilterDto;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCriteriaDto searchCriteriaDto = (SearchCriteriaDto) o;
    return Objects.equals(this.searchFilterDto, searchCriteriaDto.searchFilterDto) &&
        Objects.equals(this.selectFilterDto, searchCriteriaDto.selectFilterDto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchFilterDto, selectFilterDto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCriteriaDto {\n");
    
    sb.append("    searchFilterDto: ").append(toIndentedString(searchFilterDto)).append("\n");
    sb.append("    selectFilterDto: ").append(toIndentedString(selectFilterDto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

