/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SignCertUseInsertDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Class of signature certificate use for edit
 */
@ApiModel(description = "Class of signature certificate use for edit")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class SignCertUseSetDTO {
  @SerializedName("savePassword")
  private Boolean savePassword = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("certUseInsertList")
  private List<SignCertUseInsertDTO> certUseInsertList = null;

  public SignCertUseSetDTO savePassword(Boolean savePassword) {
    this.savePassword = savePassword;
    return this;
  }

   /**
   * Password is saved
   * @return savePassword
  **/
  @ApiModelProperty(value = "Password is saved")
  public Boolean isSavePassword() {
    return savePassword;
  }

  public void setSavePassword(Boolean savePassword) {
    this.savePassword = savePassword;
  }

  public SignCertUseSetDTO password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @ApiModelProperty(value = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public SignCertUseSetDTO certUseInsertList(List<SignCertUseInsertDTO> certUseInsertList) {
    this.certUseInsertList = certUseInsertList;
    return this;
  }

  public SignCertUseSetDTO addCertUseInsertListItem(SignCertUseInsertDTO certUseInsertListItem) {
    if (this.certUseInsertList == null) {
      this.certUseInsertList = new ArrayList<SignCertUseInsertDTO>();
    }
    this.certUseInsertList.add(certUseInsertListItem);
    return this;
  }

   /**
   * List of certificate use
   * @return certUseInsertList
  **/
  @ApiModelProperty(value = "List of certificate use")
  public List<SignCertUseInsertDTO> getCertUseInsertList() {
    return certUseInsertList;
  }

  public void setCertUseInsertList(List<SignCertUseInsertDTO> certUseInsertList) {
    this.certUseInsertList = certUseInsertList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignCertUseSetDTO signCertUseSetDTO = (SignCertUseSetDTO) o;
    return Objects.equals(this.savePassword, signCertUseSetDTO.savePassword) &&
        Objects.equals(this.password, signCertUseSetDTO.password) &&
        Objects.equals(this.certUseInsertList, signCertUseSetDTO.certUseInsertList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(savePassword, password, certUseInsertList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignCertUseSetDTO {\n");
    
    sb.append("    savePassword: ").append(toIndentedString(savePassword)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    certUseInsertList: ").append(toIndentedString(certUseInsertList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

