/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SignCertPasswordTestDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class SignCertPasswordTestDTO {
  @SerializedName("password")
  private String password = null;

  @SerializedName("otp")
  private String otp = null;

  @SerializedName("certRelatedId")
  private String certRelatedId = null;

  public SignCertPasswordTestDTO password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public SignCertPasswordTestDTO otp(String otp) {
    this.otp = otp;
    return this;
  }

   /**
   * Get otp
   * @return otp
  **/
  @ApiModelProperty(value = "")
  public String getOtp() {
    return otp;
  }

  public void setOtp(String otp) {
    this.otp = otp;
  }

  public SignCertPasswordTestDTO certRelatedId(String certRelatedId) {
    this.certRelatedId = certRelatedId;
    return this;
  }

   /**
   * For Remote Telecom Provider
   * @return certRelatedId
  **/
  @ApiModelProperty(value = "For Remote Telecom Provider")
  public String getCertRelatedId() {
    return certRelatedId;
  }

  public void setCertRelatedId(String certRelatedId) {
    this.certRelatedId = certRelatedId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignCertPasswordTestDTO signCertPasswordTestDTO = (SignCertPasswordTestDTO) o;
    return Objects.equals(this.password, signCertPasswordTestDTO.password) &&
        Objects.equals(this.otp, signCertPasswordTestDTO.otp) &&
        Objects.equals(this.certRelatedId, signCertPasswordTestDTO.certRelatedId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, otp, certRelatedId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignCertPasswordTestDTO {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("    certRelatedId: ").append(toIndentedString(certRelatedId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

