/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StampSearchFilterDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class StampSearchFilterDto {
  @SerializedName("stampInstanceApplied")
  private Integer stampInstanceApplied = null;

  @SerializedName("stampDefinitionId")
  private String stampDefinitionId = null;

  public StampSearchFilterDto stampInstanceApplied(Integer stampInstanceApplied) {
    this.stampInstanceApplied = stampInstanceApplied;
    return this;
  }

   /**
   * Get stampInstanceApplied
   * @return stampInstanceApplied
  **/
  @ApiModelProperty(value = "")
  public Integer getStampInstanceApplied() {
    return stampInstanceApplied;
  }

  public void setStampInstanceApplied(Integer stampInstanceApplied) {
    this.stampInstanceApplied = stampInstanceApplied;
  }

  public StampSearchFilterDto stampDefinitionId(String stampDefinitionId) {
    this.stampDefinitionId = stampDefinitionId;
    return this;
  }

   /**
   * Get stampDefinitionId
   * @return stampDefinitionId
  **/
  @ApiModelProperty(value = "")
  public String getStampDefinitionId() {
    return stampDefinitionId;
  }

  public void setStampDefinitionId(String stampDefinitionId) {
    this.stampDefinitionId = stampDefinitionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StampSearchFilterDto stampSearchFilterDto = (StampSearchFilterDto) o;
    return Objects.equals(this.stampInstanceApplied, stampSearchFilterDto.stampInstanceApplied) &&
        Objects.equals(this.stampDefinitionId, stampSearchFilterDto.stampDefinitionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stampInstanceApplied, stampDefinitionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StampSearchFilterDto {\n");
    
    sb.append("    stampInstanceApplied: ").append(toIndentedString(stampInstanceApplied)).append("\n");
    sb.append("    stampDefinitionId: ").append(toIndentedString(stampDefinitionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

