/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * TaskWorkNoteDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class TaskWorkNoteDTO {
  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("processId")
  private Integer processId = null;

  @SerializedName("taskWorkId")
  private Integer taskWorkId = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("userCompleteName")
  private String userCompleteName = null;

  @SerializedName("user")
  private Integer user = null;

  @SerializedName("taskWorkName")
  private String taskWorkName = null;

  public TaskWorkNoteDTO date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public TaskWorkNoteDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TaskWorkNoteDTO processId(Integer processId) {
    this.processId = processId;
    return this;
  }

   /**
   * Get processId
   * @return processId
  **/
  @ApiModelProperty(value = "")
  public Integer getProcessId() {
    return processId;
  }

  public void setProcessId(Integer processId) {
    this.processId = processId;
  }

  public TaskWorkNoteDTO taskWorkId(Integer taskWorkId) {
    this.taskWorkId = taskWorkId;
    return this;
  }

   /**
   * Get taskWorkId
   * @return taskWorkId
  **/
  @ApiModelProperty(value = "")
  public Integer getTaskWorkId() {
    return taskWorkId;
  }

  public void setTaskWorkId(Integer taskWorkId) {
    this.taskWorkId = taskWorkId;
  }

  public TaskWorkNoteDTO note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @ApiModelProperty(value = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public TaskWorkNoteDTO userCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
    return this;
  }

   /**
   * Get userCompleteName
   * @return userCompleteName
  **/
  @ApiModelProperty(value = "")
  public String getUserCompleteName() {
    return userCompleteName;
  }

  public void setUserCompleteName(String userCompleteName) {
    this.userCompleteName = userCompleteName;
  }

  public TaskWorkNoteDTO user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public TaskWorkNoteDTO taskWorkName(String taskWorkName) {
    this.taskWorkName = taskWorkName;
    return this;
  }

   /**
   * Get taskWorkName
   * @return taskWorkName
  **/
  @ApiModelProperty(value = "")
  public String getTaskWorkName() {
    return taskWorkName;
  }

  public void setTaskWorkName(String taskWorkName) {
    this.taskWorkName = taskWorkName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskWorkNoteDTO taskWorkNoteDTO = (TaskWorkNoteDTO) o;
    return Objects.equals(this.date, taskWorkNoteDTO.date) &&
        Objects.equals(this.id, taskWorkNoteDTO.id) &&
        Objects.equals(this.processId, taskWorkNoteDTO.processId) &&
        Objects.equals(this.taskWorkId, taskWorkNoteDTO.taskWorkId) &&
        Objects.equals(this.note, taskWorkNoteDTO.note) &&
        Objects.equals(this.userCompleteName, taskWorkNoteDTO.userCompleteName) &&
        Objects.equals(this.user, taskWorkNoteDTO.user) &&
        Objects.equals(this.taskWorkName, taskWorkNoteDTO.taskWorkName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, id, processId, taskWorkId, note, userCompleteName, user, taskWorkName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskWorkNoteDTO {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
    sb.append("    taskWorkId: ").append(toIndentedString(taskWorkId)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    userCompleteName: ").append(toIndentedString(userCompleteName)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    taskWorkName: ").append(toIndentedString(taskWorkName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

