/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of timestamp to insert
 */
@ApiModel(description = "Class of timestamp to insert")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class TsaInsertDTO {
  @SerializedName("description")
  private String description = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("port")
  private Integer port = null;

  @SerializedName("protocolType")
  private Integer protocolType = null;

  public TsaInsertDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TsaInsertDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url Address
   * @return url
  **/
  @ApiModelProperty(value = "Url Address")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public TsaInsertDTO username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Account Name
   * @return username
  **/
  @ApiModelProperty(value = "Account Name")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public TsaInsertDTO password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @ApiModelProperty(value = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public TsaInsertDTO enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "Enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public TsaInsertDTO port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Port Number
   * @return port
  **/
  @ApiModelProperty(value = "Port Number")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public TsaInsertDTO protocolType(Integer protocolType) {
    this.protocolType = protocolType;
    return this;
  }

   /**
   * Possible values:  0: HTTP_HTTPS  1: TCP 
   * @return protocolType
  **/
  @ApiModelProperty(value = "Possible values:  0: HTTP_HTTPS  1: TCP ")
  public Integer getProtocolType() {
    return protocolType;
  }

  public void setProtocolType(Integer protocolType) {
    this.protocolType = protocolType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TsaInsertDTO tsaInsertDTO = (TsaInsertDTO) o;
    return Objects.equals(this.description, tsaInsertDTO.description) &&
        Objects.equals(this.url, tsaInsertDTO.url) &&
        Objects.equals(this.username, tsaInsertDTO.username) &&
        Objects.equals(this.password, tsaInsertDTO.password) &&
        Objects.equals(this.enabled, tsaInsertDTO.enabled) &&
        Objects.equals(this.port, tsaInsertDTO.port) &&
        Objects.equals(this.protocolType, tsaInsertDTO.protocolType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, url, username, password, enabled, port, protocolType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TsaInsertDTO {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    protocolType: ").append(toIndentedString(protocolType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

