/*
 * Abletech.Arxivar.Server.WebApi.Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Class of the user
 */
@ApiModel(description = "Class of the user")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-11T12:02:47.866+02:00")
public class UserDTO {
  @SerializedName("user")
  private Integer user = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("businessUnit")
  private String businessUnit = null;

  @SerializedName("lang")
  private String lang = null;

  @SerializedName("respAos")
  private Boolean respAos = null;

  @SerializedName("completeName")
  private String completeName = null;

  @SerializedName("businessUnitLocked")
  private Boolean businessUnitLocked = null;

  @SerializedName("workingBusinessUnit")
  private String workingBusinessUnit = null;

  public UserDTO user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * Identifier
   * @return user
  **/
  @ApiModelProperty(value = "Identifier")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public UserDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UserDTO email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email
   * @return email
  **/
  @ApiModelProperty(value = "Email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDTO businessUnit(String businessUnit) {
    this.businessUnit = businessUnit;
    return this;
  }

   /**
   * Business Unit
   * @return businessUnit
  **/
  @ApiModelProperty(value = "Business Unit")
  public String getBusinessUnit() {
    return businessUnit;
  }

  public void setBusinessUnit(String businessUnit) {
    this.businessUnit = businessUnit;
  }

  public UserDTO lang(String lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Language
   * @return lang
  **/
  @ApiModelProperty(value = "Language")
  public String getLang() {
    return lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }

  public UserDTO respAos(Boolean respAos) {
    this.respAos = respAos;
    return this;
  }

   /**
   * Person in charge about Aos
   * @return respAos
  **/
  @ApiModelProperty(value = "Person in charge about Aos")
  public Boolean isRespAos() {
    return respAos;
  }

  public void setRespAos(Boolean respAos) {
    this.respAos = respAos;
  }

  public UserDTO completeName(String completeName) {
    this.completeName = completeName;
    return this;
  }

   /**
   * Full name
   * @return completeName
  **/
  @ApiModelProperty(value = "Full name")
  public String getCompleteName() {
    return completeName;
  }

  public void setCompleteName(String completeName) {
    this.completeName = completeName;
  }

  public UserDTO businessUnitLocked(Boolean businessUnitLocked) {
    this.businessUnitLocked = businessUnitLocked;
    return this;
  }

   /**
   * Work on single business unit
   * @return businessUnitLocked
  **/
  @ApiModelProperty(value = "Work on single business unit")
  public Boolean isBusinessUnitLocked() {
    return businessUnitLocked;
  }

  public void setBusinessUnitLocked(Boolean businessUnitLocked) {
    this.businessUnitLocked = businessUnitLocked;
  }

  public UserDTO workingBusinessUnit(String workingBusinessUnit) {
    this.workingBusinessUnit = workingBusinessUnit;
    return this;
  }

   /**
   * Business unit code of work
   * @return workingBusinessUnit
  **/
  @ApiModelProperty(value = "Business unit code of work")
  public String getWorkingBusinessUnit() {
    return workingBusinessUnit;
  }

  public void setWorkingBusinessUnit(String workingBusinessUnit) {
    this.workingBusinessUnit = workingBusinessUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDTO userDTO = (UserDTO) o;
    return Objects.equals(this.user, userDTO.user) &&
        Objects.equals(this.description, userDTO.description) &&
        Objects.equals(this.email, userDTO.email) &&
        Objects.equals(this.businessUnit, userDTO.businessUnit) &&
        Objects.equals(this.lang, userDTO.lang) &&
        Objects.equals(this.respAos, userDTO.respAos) &&
        Objects.equals(this.completeName, userDTO.completeName) &&
        Objects.equals(this.businessUnitLocked, userDTO.businessUnitLocked) &&
        Objects.equals(this.workingBusinessUnit, userDTO.workingBusinessUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, description, email, businessUnit, lang, respAos, completeName, businessUnitLocked, workingBusinessUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDTO {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    businessUnit: ").append(toIndentedString(businessUnit)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    respAos: ").append(toIndentedString(respAos)).append("\n");
    sb.append("    completeName: ").append(toIndentedString(completeName)).append("\n");
    sb.append("    businessUnitLocked: ").append(toIndentedString(businessUnitLocked)).append("\n");
    sb.append("    workingBusinessUnit: ").append(toIndentedString(workingBusinessUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

